# 🖼️ 00 - Python Express 🚀 : Maîtrisez les Bases Rapidement

Bienvenue dans cette **formation express en Python** !  
Sous **Jupyter Notebook**, nous allons utiliser deux types de cellules :  
- **Cellules de texte** avec un formatage particulier appelé **Markdown**,  
- **Cellules de code** que nous pourrons exécuter pour tester nos connaissances en Python.

Ce **notebook** alternera entre des **explications en texte** et des **exemples de code** à exécuter. Parfois, une cellule de code contiendra également des explications, dans ce cas, le texte sera commenté avec le symbole `#`.

L'objectif de ce cours est de vous fournir une **compréhension globale** du fonctionnement de **Python** et de vous permettre de l'utiliser rapidement.  
Les principales notions suivantes seront abordées :

| **No** | **Notion**                       | **Description**                                                                                                                             |
|--------|----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| *1️⃣*  | **Les variables & les types de données** | Les variables peuvent contenir plusieurs types d'information : texte, valeurs numériques, booléens, listes, dictionnaires, les arrays numpy. |
| *2️⃣*  | **Les opérations**               | Opérations de base : addition, soustraction, multiplication, division.                                                                      |
| *3️⃣*  | **Les conversions**              | Fonctions pour convertir entre différents types de données (ex. : `int()`, `float()`, `str()`).                                              |
| *4️⃣*  | **Les boucles**                  | Structures permettant de répéter des instructions (ex. : `for`, `while`).                                                                   |
| *5️⃣*  | **Les fonctions**                | Permet d'encapsuler des comportements répétitifs et d'améliorer la lisibilité du code.                                                       |
| *6️⃣*  | **Les classes et la POO**        | Introduction à la Programmation Orientée Objet : création de classes, objets, méthodes et héritage.                                           |



---

### **Objectifs du Cours**

À la fin de cette formation, vous serez capable de :
- **Comprendre et manipuler les variables et différents types de données** en Python, tels que les chaînes de caractères, les nombres, les listes, et les dictionnaires.
- **Réaliser des opérations de base** (addition, soustraction, multiplication, division) pour traiter efficacement les données.
- **Convertir des types de données**, comme transformer une chaîne en un nombre ou vice-versa, pour faciliter les manipulations.
- **Utiliser des boucles** (for, while) et des instructions de contrôle comme break et continue pour automatiser les tâches répétitives.
- **Créer et utiliser des fonctions** pour améliorer la lisibilité et la réutilisabilité du code.

Préparez-vous à plonger dans l'univers de **Python** et à expérimenter avec des **exemples pratiques** tout au long de ce notebook !



| *1️⃣*      **Les variables & les types de données** |
-------------------------------------------------------


In [2]:
ma_variable = "bonjour à toutes et à tous !"

# Afficher le contenu de notre variable avec la fonction print()

print(ma_variable)

bonjour à toutes et à tous !


In [3]:
# Vérifions le type de la variable avec la fonction dtype()
print(type(ma_variable))

<class 'str'>


In [4]:
var_entier = 10
var_decimal = 10.5
print(f"valeur: {var_entier}")

valeur: 10


In [5]:
OK = True
NOK = False
print(f"valeur: {OK}, {NOK}  - type: {type(OK), type(NOK)}")

valeur: True, False  - type: (<class 'bool'>, <class 'bool'>)


In [6]:
ma_liste = ["bonjour", True, 10] # crochets  pour les listes
print(ma_liste)

['bonjour', True, 10]


In [7]:
ma_liste[0]

'bonjour'

In [8]:
ma_liste[0] = 8999
ma_liste

[8999, True, 10]

In [9]:
# 1. append() : Ajouter un élément à la fin
ma_liste = ["bonjour", True, 10]
ma_liste.append("nouvel élément")
print("Après append :", ma_liste)  

Après append : ['bonjour', True, 10, 'nouvel élément']


In [10]:
# 2. extend() : Ajouter plusieurs éléments à la liste initiale
ma_liste.extend([20, False, "autre élément"])
print("Après extend :", ma_liste)  

Après extend : ['bonjour', True, 10, 'nouvel élément', 20, False, 'autre élément']


In [11]:
# 3. remove() : Supprimer la première occurrence d'un élément
ma_liste.remove(True)  # True sera supprimé (le premier trouvé)
print("Après remove :", ma_liste)  

Après remove : ['bonjour', 10, 'nouvel élément', 20, False, 'autre élément']


In [12]:
# 4. pop() : Supprimer et retourner un élément
dernier_element = ma_liste.pop(0)  # Par défaut, supprime le dernier élément
print("Après pop :", ma_liste)  
# Résultat : ["bonjour", 10, "nouvel élément", 20, False]
print("Élément supprimé avec pop :", dernier_element)  

Après pop : [10, 'nouvel élément', 20, False, 'autre élément']
Élément supprimé avec pop : bonjour


In [13]:
# 5. sort() : Trier les éléments
# Créons une nouvelle liste uniquement avec des nombres pour utiliser sort()
liste_nombres = [3, 1, 4, 1, 5]
liste_nombres.sort()
print("Liste triée :", liste_nombres)

Liste triée : [1, 1, 3, 4, 5]


In [14]:
# Définition du dictionnaire
mon_dict = {"ma_clef_1": 45959392, "ma_clef_2": True, "ma_clef_3": '@!!à~&,;'}

# 1. get() : Récupérer la valeur associée à une clé
valeur = mon_dict.get("ma_clef_1")
print("Valeur obtenue avec get :", valeur)  

Valeur obtenue avec get : 45959392


In [15]:
# 2. keys() : Obtenir toutes les clés du dictionnaire
cles = mon_dict.keys()
print("Clés du dictionnaire :", cles)  

Clés du dictionnaire : dict_keys(['ma_clef_1', 'ma_clef_2', 'ma_clef_3'])


In [16]:
# 3. values() : Obtenir toutes les valeurs du dictionnaire
valeurs = mon_dict.values()
print("Valeurs du dictionnaire :", valeurs)  

Valeurs du dictionnaire : dict_values([45959392, True, '@!!à~&,;'])


In [17]:
# 4. items() : Obtenir toutes les paires clé-valeur sous forme de tuples
paires = mon_dict.items()
print("Paires clé-valeur :", paires)  

mon_tuple = ("maclef", 6999)
print(mon_tuple, type(mon_tuple))

Paires clé-valeur : dict_items([('ma_clef_1', 45959392), ('ma_clef_2', True), ('ma_clef_3', '@!!à~&,;')])
('maclef', 6999) <class 'tuple'>


In [18]:
# 5. pop() : Supprimer une clé spécifique et récupérer sa valeur
valeur_supprimee = mon_dict.pop("ma_clef_2")
print("Valeur supprimée avec pop :", valeur_supprimee)  
print("Dictionnaire après pop :", mon_dict)  


Valeur supprimée avec pop : True
Dictionnaire après pop : {'ma_clef_1': 45959392, 'ma_clef_3': '@!!à~&,;'}


Ci desous un tableau récapitulatif qui compare les dictionnaires aux listes.

| **Critère**                | **Liste** (list)                                           | **Dictionnaire** (dict)                                         |
|----------------------------|------------------------------------------------------------|-----------------------------------------------------------------|
| **Type de données**         | Une séquence ordonnée d'éléments.                          | Une collection de paires clé-valeur (éléments associés à une clé). |
| **Ordre des éléments**      | Les éléments sont ordonnés (indexés par position).         | Les éléments ne sont pas ordonnés (les clés ne suivent pas un ordre particulier). |
| **Accès aux éléments**      | Par **index** (entier), par exemple `ma_liste[0]`.         | Par **clé** (unique), par exemple `mon_dict["clé1"]`.           |
| **Modifiabilité**           | Les éléments sont **mutables**, vous pouvez les changer.  | Les valeurs sont **mutables**, mais les clés doivent être immuables. |
| **Types de données des éléments** | Les éléments peuvent être de n'importe quel type (mélange possible). | Les clés doivent être **hashables** (types immuables comme `str`, `int`), et les valeurs peuvent être de n'importe quel type. |
| **Duplication des éléments** | Autorisée : Une liste peut avoir des éléments dupliqués.   | **Pas de duplication des clés** : chaque clé est unique.      |
| **Méthodes courantes**      | `append()`, `extend()`, `remove()`, `pop()`, `sort()`.      | `get()`, `keys()`, `values()`, `items()`, `pop()`.              |
| **Performance de recherche**| Recherche par **indexation**, ce qui est rapide.            | Recherche par **clé** avec une complexité en temps constant (`O(1)` en moyenne). |
| **Utilisation principale**  | Utilisée pour stocker des séquences ordonnées d'éléments.  | Utilisée pour stocker des paires de données associant une clé à une valeur. |


In [19]:
import numpy as np 
# NumPy : une bibliothèque essentielle pour le calcul scientifique en Python.
# Elle permet de manipuler efficacement des tableaux multidimensionnels et de réaliser des calculs mathématiques rapides.

# Création d'un tableau 2D (matrice de 2 lignes et 3 colonnes)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Tableau 2D:")
print(array_2d)  # Affiche le tableau 2D
print(f"Shape: {array_2d.shape}")  # Affiche les dimensions du tableau (lignes, colonnes)
# Ici, shape=(2, 3) indique qu'il y a 2 lignes et 3 colonnes.
print("\n")

# Création d'un tableau 3D (structure contenant plusieurs matrices 2D)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Tableau 3D:")
print(array_3d)  # Affiche le tableau 3D
print(f"Shape: {array_3d.shape}")  # Affiche les dimensions du tableau (profondeur, lignes, colonnes)
# Ici, shape=(2, 2, 3) indique :
# - 2 : Profondeur (nombre de sous-tableaux 2D, ou "couches").
# - 2 : Nombre de lignes dans chaque sous-tableau 2D.
# - 3 : Nombre de colonnes dans chaque sous-tableau 2D.
print("\n")

ModuleNotFoundError: No module named 'numpy'

In [ ]:
# Accéder à tous les éléments
array_1d = np.array([10, 20, 30, 40, 50])
print("Tous les éléments (array_1d[:]):", array_1d[:])  # [10, 20, 30, 40, 50]

# Accéder à un intervalle d'éléments
print("Éléments de l'indice 1 à 3 (array_1d[1:4]):", array_1d[1:4])  # [20, 30, 40]

Tous les éléments (array_1d[:]): [10 20 30 40 50]
Éléments de l'indice 1 à 3 (array_1d[1:4]): [20 30 40]


In [ ]:
# Ajout d'une dimension à un tableau 1D avec np.newaxis
array_1d = np.array([1, 2, 3])
print("Tableau 1D avant np.newaxis:")
print(array_1d)
print(f"Shape: {array_1d.shape}")

# Ajouter une dimension pour transformer 1D en 2D (comme une colonne)
array_2d_col = array_1d[:, np.newaxis]
print("\nTableau 1D transformé en 2D (colonne) avec np.newaxis:")
print(array_2d_col)
print(f"Shape: {array_2d_col.shape}")

# Ajouter une dimension pour transformer 1D en 2D (comme une ligne)
array_2d_row = array_1d[np.newaxis, :]
print("\nTableau 1D transformé en 2D (ligne) avec np.newaxis:")
print(array_2d_row)
print(f"Shape: {array_2d_row.shape}")

# Ajout d'une dimension à un tableau 2D pour créer un tableau 3D
array_3d_from_2d = array_2d[:, :, np.newaxis]
print("\nTableau 2D transformé en 3D avec np.newaxis:")
print(array_3d_from_2d)
print(f"Shape: {array_3d_from_2d.shape}")

Tableau 1D avant np.newaxis:
[1 2 3]
Shape: (3,)

Tableau 1D transformé en 2D (colonne) avec np.newaxis:
[[1]
 [2]
 [3]]
Shape: (3, 1)

Tableau 1D transformé en 2D (ligne) avec np.newaxis:
[[1 2 3]]
Shape: (1, 3)

Tableau 2D transformé en 3D avec np.newaxis:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
Shape: (2, 3, 1)


| *2️⃣*      **Les opérations** |
-------------------------------------------------------

❓ **>>>** Vous allez faire vos courses chez le maraîcher bio du coin. À partir de cette liste de course, calculez le prix que vous devrez payer pour chaque type de légumes.


| Légume              | Prix              | Quantité         | Remarque          |
|---------------------|-------------------|------------------|-------------------|
| Carottes            | 2,50€/kg          | 1 kg             |                   |
| Poireaux            | 1,99€ les 3       | 2 bottes         |                   |
| Brocolis            | 3,75€ le kilo     | 600g             |                   |
| Courgettes          | 1,80€/kg          | 800g             |                   |
| Chou-fleur          | 4,00€ la pièce    | 1 chou           |                   |
| Tomates cerises     | 3,50€/kg          | 500g             | En promo, -15%    |
| Pommes de terre     | 1,20€/kg          | 2,5 kg           |                   |
| Salade Romaine      | 1,50€ l'unité     | 1 salade         |                   |


In [ ]:
# Calcul le prix total ici
# Calcul manuel direct sans définir de variables intermédiaires
prix_total = (
    (2.50 * 1) +  # Carottes
    (1.99 * 2) +  # Poireaux
    (3.75 * 0.6) +  # Brocolis
    (1.80 * 0.8) +  # Courgettes
    (4.00 * 1) +  # Chou-fleur
    (3.50 * 0.5 * (1 - 0.15)) +  # Tomates cerises avec promo
    (1.20 * 2.5) +  # Pommes de terre
    (1.50 * 1)  # Salade Romaine
)

prix_total

In [ ]:
# Calcul de 2 élevé à la puissance 3 (2^3)
resultat_puissance = 2 ** 3
print(resultat_puissance)  # Affiche 8

# Division de 10 par 3 (division entière)
resultat_division_euclidienne = 10 // 3
print(resultat_division_euclidienne)  # Affiche 3

# Reste de la division de 10 par 3
resultat_modulo = 10 % 3
print(resultat_modulo)  # Affiche 1

| *3️⃣*      **Les conversions**** |
-------------------------------------------------------

In [ ]:
# Conversion en entier (int)
string_to_int = int("42")
print(string_to_int)  # Affiche 42
float_to_int = int(3.99)
print(float_to_int)  # Affiche 3

# Conversion en flottant (float)
string_to_float = float("42.5")
print(string_to_float)  # Affiche 42.5
int_to_float = float(42)
print(int_to_float)  # Affiche 42.0

# Conversion en chaîne de caractères (str)
int_to_string = str(42)
print(int_to_string)  # Affiche "42"
float_to_string = str(42.5)
print(float_to_string)  # Affiche "42.5"

# Conversion en liste (list)
string_to_list = list("hello")
print(string_to_list)  # Affiche ['h', 'e', 'l', 'l', 'o']

# Conversion en tuple (tuple)
list_to_tuple = tuple([1, 2, 3])
print(list_to_tuple)  # Affiche (1, 2, 3)

| *4️⃣*      ****Les boucles**** |
-------------------------------------------------------


In [ ]:
# 1️⃣ Boucle for avec une liste
print("Exemple 1: Boucle for avec une liste")
ma_liste = [10, 20, 30, 40, 50]
for x in ma_liste:
    print(x)  # Affiche chaque élément de la liste

# 2️⃣ Boucle for avec un dictionnaire
print("\nExemple 2: Boucle for avec un dictionnaire")
mon_dict = {"a": 1, "b": 2, "c": 3, "d": 4}
for cle, valeur in mon_dict.items():
    print(f"Clé: {cle}, Valeur: {valeur}")  # Affiche la clé et la valeur du dictionnaire

# 3️⃣ Boucle while avec une liste
print("\nExemple 3: Boucle while avec une liste")
compteur = 0
while compteur < len(ma_liste):
    print(ma_liste[compteur])  # Affiche chaque élément de la liste
    compteur += 1 # compteur = compteur +1

# 4️⃣ Boucle while avec un dictionnaire (par les clés)
print("\nExemple 4: Boucle while avec un dictionnaire")
cle_dict = list(mon_dict.keys())
index = 0
while index < len(cle_dict):
    cle = cle_dict[index]
    print(f"Clé: {cle}, Valeur: {mon_dict[cle]}")  # Affiche la clé et la valeur du dictionnaire
    index += 1

# 5️⃣ Utilisation de break dans une boucle sur une liste
print("\nExemple 5: Utilisation de break dans une boucle avec une liste")
for element in ma_liste:
    if element == 30:
        break  # Sort de la boucle lorsque l'élément est 30
    print(element)  # Affiche 10, 20

# 6️⃣ Utilisation de continue dans une boucle sur un dictionnaire
print("\nExemple 6: Utilisation de continue dans une boucle avec un dictionnaire")
for cle, valeur in mon_dict.items():
    if valeur == 2:
        continue  # Ignore l'élément où la valeur est 2
    print(f"Clé: {cle}, Valeur: {valeur}")  # Affiche les éléments sauf ceux où la valeur est 2


In [ ]:
# Utilisation de break
print("Exemple avec break :")
print(ma_liste)
for element in ma_liste:
    if element == 30:
        print("Valeur 30 trouvée, sortie de la boucle.")
        break  # Sort de la boucle dès que la valeur 25 est trouvée
    print(element)


In [ ]:
# Utilisation de continue
print("\nExemple avec continue :")
for element in ma_liste:
    if element == 20:
        print("Valeur 20 trouvée, on saute cet élément.")
        continue  # Ignore l'élément 20 et passe à l'itération suivante
    print(element)


| *5️⃣*      **Les fonctions** |
-------------------------------------------------------


In [ ]:
# Fonction qui additionne les éléments d'une liste
def additionner_liste(ma_liste):
    total = sum(ma_liste)  # Utilisation de la fonction sum() pour additionner les éléments
    return total

# Exemple de liste
ma_liste = [10, 20, 30, 40, 50]

# Appel de la fonction
resultat = additionner_liste(ma_liste)
print(f"Somme des éléments de la liste : {resultat}")  # Affiche 150


| *6️⃣*      **Programmation orientée objet (POO)** |
-------------------------------------------------------


### Exemple de l'utilisation d'une Classe

Dans une classe Python, **`__init__`** est une méthode spéciale qui **doit être utilisée** pour initialiser un objet lorsqu'on le crée. Elle est appelée automatiquement lors de la création d'un nouvel objet et sert à définir les attributs de l'objet (comme son nom, âge, etc.).

- **`__init__`** : Méthode qui initialise l'objet avec des valeurs dès sa création.
- **`self`** : Représente l'instance de l'objet en cours. C'est comme dire "ce chien" ou "cet animal".
- **`super()`** : Permet d'appeler la méthode de la classe parente sans réécrire du code.

Dans l'exemple ci-dessous :
- La classe **`Animal`** est une base pour créer des animaux. Elle contient les attributs `nom` et `age`.
- La classe **`Chien`** hérite de **`Animal`**, ajoute un attribut `race` et redéfinit la méthode `parler()` pour un comportement spécifique aux chiens (aboyer).

### Exemple de code



In [ ]:
class Animal:
    def __init__(self, nom, age):
        """Initialise un animal avec un nom et un âge."""
        self.nom = nom  # Attribut 'nom' de l'animal
        self.age = age  # Attribut 'age' de l'animal
        print(f"{self.nom} est un animal âgé de {self.age} ans.")

    def parler(self):
        """Comportement générique pour un animal qui parle."""
        print(f"{self.nom} fait un bruit.")

class Chien(Animal):
    def __init__(self, nom, age, race):
        """Initialise un chien avec son nom, âge et sa race."""
        super().__init__(nom, age)  # Appelle le constructeur de la classe parente (Animal)
        self.race = race  # Attribut spécifique aux chiens
        print(f"Il est de race {self.race}.")  # Affiche la race du chien

    def parler(self):
        """Comportement spécifique aux chiens : aboyer."""
        print(f"{self.nom} aboie.")  # Le chien aboie

# Création d'une instance de Chien
mon_chien = Chien("Rex", 5, "Labrador")

# Appel de la méthode parler, qui sera spécifique à la classe Chien
mon_chien.parler()